# Generated by Django 4.1.1 on 2023-05-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought',
        ),
        migrations.RemoveField(
            model_name='product',
            name='used',
        ),
    ]
