# Generated by Django 4.1.1 on 2023-05-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0003_remove_product_bought_remove_product_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
