# Generated by Django 4.1.1 on 2023-05-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0007_remove_orders_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zip_code',
            new_name='pin_code',
        ),
    ]
